name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Run Go Vet
        run: |
          go vet ./...
      - name: Run Go Test and generate coverage report
        run: |
          go test -race -v ./... -coverprofile=coverage.out
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
      - name: Run Go Fmt
        run: |
          files=$(go fmt ./...)
          if [ -n "$files" ]; then
            echo "Please run gofmt on these files ..."
            echo "$files"
            exit 1
          fi
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
         path: coverage.out
         name: Coverage-report
      - name: Display coverage report 
        run: go tool cover -func=coverage.out
      - name: Build Go
        run: go build ./...
